name: Build and Release Libraries

permissions:
  contents: write
  packages: read

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true


jobs:
  add-libs:
    runs-on: ubuntu-latest

    steps:
      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Libraries
        run: |
          TAG=${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.event.inputs.tag }}
          docker run --rm -v ./libs:/libs -e TAG=$TAG ghcr.io/codewithkyrian/transformers-php:latest
          ls libs

      - name: Add Libraries to Release
        uses:  softprops/action-gh-release@v2
        with:
          files: |
            libs/*