name: Build and Release Libraries

on:
  release:
    types:
      - published

  workflow_dispatch:
    inputs:
      tag:
        description: 'Release Tag'
        required: true


jobs:
  package:
    runs-on: ubuntu-latest
    container:
      image: codewithkyrian/transformersphp-libs:latest
      env:
        TAG: ${{ startsWith(github.ref, 'refs/tags/') && github.ref_name || github.event.inputs.tag }}

    steps:
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: /packages/*